# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: broker.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'broker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62roker.proto\x12\x06\x62roker\"$\n\x13SubscriptionRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"|\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12.\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32 .broker.PublishRequest.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\"\n\x0fPublishResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"n\n\x07Message\x12\r\n\x05topic\x18\x01 \x01(\t\x12\'\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x19.broker.Message.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x88\x01\n\rBrokerService\x12;\n\tSubscribe\x12\x1b.broker.SubscriptionRequest\x1a\x0f.broker.Message0\x01\x12:\n\x07Publish\x12\x16.broker.PublishRequest\x1a\x17.broker.PublishResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'broker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHREQUEST_DATAENTRY']._loaded_options = None
  _globals['_PUBLISHREQUEST_DATAENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGE_DATAENTRY']._loaded_options = None
  _globals['_MESSAGE_DATAENTRY']._serialized_options = b'8\001'
  _globals['_SUBSCRIPTIONREQUEST']._serialized_start=24
  _globals['_SUBSCRIPTIONREQUEST']._serialized_end=60
  _globals['_PUBLISHREQUEST']._serialized_start=62
  _globals['_PUBLISHREQUEST']._serialized_end=186
  _globals['_PUBLISHREQUEST_DATAENTRY']._serialized_start=143
  _globals['_PUBLISHREQUEST_DATAENTRY']._serialized_end=186
  _globals['_PUBLISHRESPONSE']._serialized_start=188
  _globals['_PUBLISHRESPONSE']._serialized_end=222
  _globals['_MESSAGE']._serialized_start=224
  _globals['_MESSAGE']._serialized_end=334
  _globals['_MESSAGE_DATAENTRY']._serialized_start=143
  _globals['_MESSAGE_DATAENTRY']._serialized_end=186
  _globals['_BROKERSERVICE']._serialized_start=337
  _globals['_BROKERSERVICE']._serialized_end=473
# @@protoc_insertion_point(module_scope)
